<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="2" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-22T11:36:29 IST" name="Suite" finished-at="2023-12-22T11:36:37 IST" duration-ms="7411">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidations.ErrorValidate()[pri:0, instance:SeleniumFramework.test.ErrorValidations@3cce5371]" name="ErrorValidate" class="SeleniumFramework.test.ErrorValidations"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="E2E.submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" name="submitOrder" class="SeleniumFramework.test.E2E"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2023-12-22T11:36:29 IST" name="Error Validations" finished-at="2023-12-22T11:36:35 IST" duration-ms="5566">
      <class name="SeleniumFramework.test.ErrorValidations">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.test.ErrorValidations@3cce5371]" started-at="2023-12-22T11:36:29 IST" name="launchApplication" finished-at="2023-12-22T11:36:34 IST" duration-ms="4739" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ErrorValidate()[pri:0, instance:SeleniumFramework.test.ErrorValidations@3cce5371]" started-at="2023-12-22T11:36:34 IST" name="ErrorValidate" finished-at="2023-12-22T11:36:35 IST" duration-ms="690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ErrorValidate -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.test.ErrorValidations@3cce5371]" started-at="2023-12-22T11:36:35 IST" name="tearDown" finished-at="2023-12-22T11:36:35 IST" duration-ms="100" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SeleniumFramework.test.ErrorValidations -->
    </test> <!-- Error Validations -->
    <test started-at="2023-12-22T11:36:29 IST" name="End to End" finished-at="2023-12-22T11:36:37 IST" duration-ms="7411">
      <class name="SeleniumFramework.test.E2E">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" started-at="2023-12-22T11:36:29 IST" name="launchApplication" finished-at="2023-12-22T11:36:33 IST" duration-ms="3362" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" started-at="2023-12-22T11:36:33 IST" name="submitOrder" data-provider="getData" finished-at="2023-12-22T11:36:33 IST" duration-ms="717" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Rohit&1409, product=ZARA COAT 3, email=rahulpawar1409@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at SeleniumFramework.PageObject.ProductCatalogue.addProductToCart(ProductCatalogue.java:51)
at SeleniumFramework.test.E2E.submitOrder(E2E.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" started-at="2023-12-22T11:36:34 IST" name="tearDown" finished-at="2023-12-22T11:36:34 IST" duration-ms="59" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" started-at="2023-12-22T11:36:34 IST" name="launchApplication" finished-at="2023-12-22T11:36:36 IST" duration-ms="1712" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" started-at="2023-12-22T11:36:36 IST" name="submitOrder" data-provider="getData" finished-at="2023-12-22T11:36:36 IST" duration-ms="670" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Iamking@000, product=ADIDAS ORIGINAL, email=shetty@gmail.com}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.findElement(org.openqa.selenium.By)" because "prod" is null
at SeleniumFramework.PageObject.ProductCatalogue.addProductToCart(ProductCatalogue.java:51)
at SeleniumFramework.test.E2E.submitOrder(E2E.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" started-at="2023-12-22T11:36:36 IST" name="tearDown" finished-at="2023-12-22T11:36:37 IST" duration-ms="88" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method signature="OrderHistory()[pri:0, instance:SeleniumFramework.test.E2E@5032714f]" started-at="2023-12-22T11:36:37 IST" name="OrderHistory" finished-at="2023-12-22T11:36:37 IST" depends-on-methods="SeleniumFramework.test.E2E.submitOrder" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method SeleniumFramework.test.E2E.OrderHistory() on instance SeleniumFramework.test.E2E@5032714f depends on not successfully finished methods 
[SeleniumFramework.test.E2E.submitOrder() on instance SeleniumFramework.test.E2E@5032714f]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method SeleniumFramework.test.E2E.OrderHistory() on instance SeleniumFramework.test.E2E@5032714f depends on not successfully finished methods 
[SeleniumFramework.test.E2E.submitOrder() on instance SeleniumFramework.test.E2E@5032714f]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OrderHistory -->
      </class> <!-- SeleniumFramework.test.E2E -->
    </test> <!-- End to End -->
  </suite> <!-- Suite -->
</testng-results>
